name: macOS build

on: [push, pull_request]

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Toolchain Cache
      id: mac-toolchain
      uses: actions/cache@v3
      with:
        path: ~/mac-toolchain
        key: mac-toolchain

    - name: Cargo-C Toolchain Cache
      id: mac-cargo-c-toolchain
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/cargo-capi
          ~/.cargo/bin/cargo-cbuild
          ~/.cargo/bin/cargo-cinstall
        key: mac-cargo-c-toolchain

    - name: Setup Environment
      run: |
        echo ~/mac-toolchain/bin >> $GITHUB_PATH
        echo ~/.cargo/env >> $GITHUB_PATH

    - name: Setup Toolchain
      if: steps.mac-toolchain.outputs.cache-hit != 'true'
      run: |
        scripts/mac-toolchain-build ~/mac-toolchain

    - name: Setup Rust Toolchain
      run: |
        rustup target add aarch64-apple-darwin

    - name: Setup Cargo-C Toolchain
      if: steps.mac-cargo-c-toolchain.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-c

    - name: Build HandBrake
      run: |
        ./configure --disable-x265
        cd build
        make ub && make pkg.create

    - name: Upload Assets
      uses: actions/upload-artifact@v3
      with:
        name: HandBrake-macos
        path: ./build/pkg
