name: Windows Build (ARM)

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_mingw:
    name: CLI / LibHB (ARM)
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5

    - name: Cargo-C Toolchain Cache
      id: windows-arm-cargo-c-toolchain
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-capi
          ~/.cargo/bin/cargo-cbuild
          ~/.cargo/bin/cargo-cinstall
        key: windows-arm-cargo-c-toolchain


    - name: Setup Environment
      run: |
        sudo apt-get install automake autoconf build-essential libtool libtool-bin make nasm patch tar yasm zlib1g-dev ninja-build gzip pax
        sudo pip3 install meson
        rustup target add aarch64-pc-windows-msvc

    - name: Setup Toolchain
      run: |
        wget https://github.com/HandBrake/HandBrake-toolchains/releases/download/1.0/llvm-mingw-20231128-msvcrt-ubuntu-20.04-x86_64.tar.xz
        SHA=$(sha1sum llvm-mingw-20231128-msvcrt-ubuntu-20.04-x86_64.tar.xz)
        EXPECTED="fd5a33e18e460406f900c8e74ed6580eba3fb668  llvm-mingw-20231128-msvcrt-ubuntu-20.04-x86_64.tar.xz"
        if [ "$SHA" == "$EXPECTED" ];
        then
            echo "Toolchain Verified. Extracting ..."
            mkdir toolchains
            mv llvm-mingw-20231128-msvcrt-ubuntu-20.04-x86_64.tar.xz toolchains
            cd toolchains
            tar xvf llvm-mingw-20231128-msvcrt-ubuntu-20.04-x86_64.tar.xz
        else
            echo "Toolchain Verification FAILED. Exiting!"
            return -1
        fi

    - name: Setup Cargo-C Toolchain
      if: steps.windows-arm-cargo-c-toolchain.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-c

    - name: Build CLI and LibHB
      run: |
        export PATH="/home/runner/work/HandBrake/HandBrake/toolchains/llvm-mingw-20231128-msvcrt-ubuntu-20.04-x86_64/bin:${PATH}"
        export PATH=/usr/bin:$PATH
        ./configure --cross=aarch64-w64-mingw32 --enable-mf --launch-jobs=0 --launch
        cd build
        make pkg.create.zip

    - name: Upload HandBrakeCLI
      uses: actions/upload-artifact@v4
      with:
        name: HandBrakeCLI
        path: ./build/HandBrakeCLI.exe

    - name: Upload LibHB
      uses: actions/upload-artifact@v4
      with:
        name: LibHandBrake
        path: ./build/libhb/hb.dll
